version: '3'
services:
	database:
		build:
			context: './database'
		container_name: github-issues-remake-db
		tty: true
		ports:
			- "5432:5432"
	server:
		build:
			context: ./
		container_name: github-issues-remake-server
		ports:
			-	"8888:8888"
		tty: true
		depends_on:
			- database
